name: Generate PHP Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.10' # Spécifie la version de PHP que tu utilises

      - name: Install Composer dependencies
        run: composer install

      - name: Generate Documentation
        run: ./vendor/bin/phpdoc -d ./src -t ./output

      - name: Push to Wiki
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          cp -R ./output/* wiki/
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update documentation"
          git push
